FROM python:3.9-slim-buster

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3-dev

COPY requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

COPY .env ./.env
COPY api ./api

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]